// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projects/searchengine/src/main/java/entity/proto/searchengine.proto

package entity.proto;

public final class SearchModel {
  private SearchModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:distributed.search.SearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string search_term = 1;</code>
     */
    boolean hasSearchTerm();
    /**
     * <code>required string search_term = 1;</code>
     */
    java.lang.String getSearchTerm();
    /**
     * <code>required string search_term = 1;</code>
     */
    com.google.protobuf.ByteString
        getSearchTermBytes();
  }
  /**
   * Protobuf type {@code distributed.search.SearchRequest}
   */
  public  static final class SearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:distributed.search.SearchRequest)
      SearchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchRequest() {
      searchTerm_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              searchTerm_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return entity.proto.SearchModel.internal_static_distributed_search_SearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return entity.proto.SearchModel.internal_static_distributed_search_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              entity.proto.SearchModel.SearchRequest.class, entity.proto.SearchModel.SearchRequest.Builder.class);
    }

    private int bitField0_;
    public static final int SEARCH_TERM_FIELD_NUMBER = 1;
    private volatile java.lang.Object searchTerm_;
    /**
     * <code>required string search_term = 1;</code>
     */
    public boolean hasSearchTerm() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string search_term = 1;</code>
     */
    public java.lang.String getSearchTerm() {
      java.lang.Object ref = searchTerm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          searchTerm_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string search_term = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSearchTermBytes() {
      java.lang.Object ref = searchTerm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchTerm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSearchTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, searchTerm_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, searchTerm_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof entity.proto.SearchModel.SearchRequest)) {
        return super.equals(obj);
      }
      entity.proto.SearchModel.SearchRequest other = (entity.proto.SearchModel.SearchRequest) obj;

      if (hasSearchTerm() != other.hasSearchTerm()) return false;
      if (hasSearchTerm()) {
        if (!getSearchTerm()
            .equals(other.getSearchTerm())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSearchTerm()) {
        hash = (37 * hash) + SEARCH_TERM_FIELD_NUMBER;
        hash = (53 * hash) + getSearchTerm().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static entity.proto.SearchModel.SearchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static entity.proto.SearchModel.SearchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static entity.proto.SearchModel.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static entity.proto.SearchModel.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static entity.proto.SearchModel.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static entity.proto.SearchModel.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static entity.proto.SearchModel.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(entity.proto.SearchModel.SearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code distributed.search.SearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:distributed.search.SearchRequest)
        entity.proto.SearchModel.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return entity.proto.SearchModel.internal_static_distributed_search_SearchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return entity.proto.SearchModel.internal_static_distributed_search_SearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                entity.proto.SearchModel.SearchRequest.class, entity.proto.SearchModel.SearchRequest.Builder.class);
      }

      // Construct using entity.proto.SearchModel.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        searchTerm_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return entity.proto.SearchModel.internal_static_distributed_search_SearchRequest_descriptor;
      }

      @java.lang.Override
      public entity.proto.SearchModel.SearchRequest getDefaultInstanceForType() {
        return entity.proto.SearchModel.SearchRequest.getDefaultInstance();
      }

      @java.lang.Override
      public entity.proto.SearchModel.SearchRequest build() {
        entity.proto.SearchModel.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public entity.proto.SearchModel.SearchRequest buildPartial() {
        entity.proto.SearchModel.SearchRequest result = new entity.proto.SearchModel.SearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.searchTerm_ = searchTerm_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof entity.proto.SearchModel.SearchRequest) {
          return mergeFrom((entity.proto.SearchModel.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(entity.proto.SearchModel.SearchRequest other) {
        if (other == entity.proto.SearchModel.SearchRequest.getDefaultInstance()) return this;
        if (other.hasSearchTerm()) {
          bitField0_ |= 0x00000001;
          searchTerm_ = other.searchTerm_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSearchTerm()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        entity.proto.SearchModel.SearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (entity.proto.SearchModel.SearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object searchTerm_ = "";
      /**
       * <code>required string search_term = 1;</code>
       */
      public boolean hasSearchTerm() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string search_term = 1;</code>
       */
      public java.lang.String getSearchTerm() {
        java.lang.Object ref = searchTerm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            searchTerm_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string search_term = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSearchTermBytes() {
        java.lang.Object ref = searchTerm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          searchTerm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string search_term = 1;</code>
       */
      public Builder setSearchTerm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        searchTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string search_term = 1;</code>
       */
      public Builder clearSearchTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        searchTerm_ = getDefaultInstance().getSearchTerm();
        onChanged();
        return this;
      }
      /**
       * <code>required string search_term = 1;</code>
       */
      public Builder setSearchTermBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        searchTerm_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:distributed.search.SearchRequest)
    }

    // @@protoc_insertion_point(class_scope:distributed.search.SearchRequest)
    private static final entity.proto.SearchModel.SearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new entity.proto.SearchModel.SearchRequest();
    }

    public static entity.proto.SearchModel.SearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
      @java.lang.Override
      public SearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public entity.proto.SearchModel.SearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:distributed.search.SearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    java.util.List<entity.proto.SearchModel.SearchResponse.DocumentStats> 
        getDocumentsList();
    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    entity.proto.SearchModel.SearchResponse.DocumentStats getDocuments(int index);
    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    int getDocumentsCount();
    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    java.util.List<? extends entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder> 
        getDocumentsOrBuilderList();
    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder getDocumentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code distributed.search.SearchResponse}
   */
  public  static final class SearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:distributed.search.SearchResponse)
      SearchResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchResponse.newBuilder() to construct.
    private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchResponse() {
      documents_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                documents_ = new java.util.ArrayList<entity.proto.SearchModel.SearchResponse.DocumentStats>();
                mutable_bitField0_ |= 0x00000001;
              }
              documents_.add(
                  input.readMessage(entity.proto.SearchModel.SearchResponse.DocumentStats.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          documents_ = java.util.Collections.unmodifiableList(documents_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              entity.proto.SearchModel.SearchResponse.class, entity.proto.SearchModel.SearchResponse.Builder.class);
    }

    public interface DocumentStatsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:distributed.search.SearchResponse.DocumentStats)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>required double score = 2;</code>
       */
      boolean hasScore();
      /**
       * <code>required double score = 2;</code>
       */
      double getScore();

      /**
       * <code>required int64 size = 3;</code>
       */
      boolean hasSize();
      /**
       * <code>required int64 size = 3;</code>
       */
      long getSize();

      /**
       * <code>optional string author = 4;</code>
       */
      boolean hasAuthor();
      /**
       * <code>optional string author = 4;</code>
       */
      java.lang.String getAuthor();
      /**
       * <code>optional string author = 4;</code>
       */
      com.google.protobuf.ByteString
          getAuthorBytes();
    }
    /**
     * Protobuf type {@code distributed.search.SearchResponse.DocumentStats}
     */
    public  static final class DocumentStats extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:distributed.search.SearchResponse.DocumentStats)
        DocumentStatsOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DocumentStats.newBuilder() to construct.
      private DocumentStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DocumentStats() {
        name_ = "";
        author_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new DocumentStats();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DocumentStats(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                name_ = bs;
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                score_ = input.readDouble();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                size_ = input.readInt64();
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                author_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_DocumentStats_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_DocumentStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                entity.proto.SearchModel.SearchResponse.DocumentStats.class, entity.proto.SearchModel.SearchResponse.DocumentStats.Builder.class);
      }

      private int bitField0_;
      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SCORE_FIELD_NUMBER = 2;
      private double score_;
      /**
       * <code>required double score = 2;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double score = 2;</code>
       */
      public double getScore() {
        return score_;
      }

      public static final int SIZE_FIELD_NUMBER = 3;
      private long size_;
      /**
       * <code>required int64 size = 3;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int64 size = 3;</code>
       */
      public long getSize() {
        return size_;
      }

      public static final int AUTHOR_FIELD_NUMBER = 4;
      private volatile java.lang.Object author_;
      /**
       * <code>optional string author = 4;</code>
       */
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string author = 4;</code>
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            author_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string author = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasScore()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSize()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeDouble(2, score_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeInt64(3, size_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, author_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, score_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, size_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, author_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof entity.proto.SearchModel.SearchResponse.DocumentStats)) {
          return super.equals(obj);
        }
        entity.proto.SearchModel.SearchResponse.DocumentStats other = (entity.proto.SearchModel.SearchResponse.DocumentStats) obj;

        if (hasName() != other.hasName()) return false;
        if (hasName()) {
          if (!getName()
              .equals(other.getName())) return false;
        }
        if (hasScore() != other.hasScore()) return false;
        if (hasScore()) {
          if (java.lang.Double.doubleToLongBits(getScore())
              != java.lang.Double.doubleToLongBits(
                  other.getScore())) return false;
        }
        if (hasSize() != other.hasSize()) return false;
        if (hasSize()) {
          if (getSize()
              != other.getSize()) return false;
        }
        if (hasAuthor() != other.hasAuthor()) return false;
        if (hasAuthor()) {
          if (!getAuthor()
              .equals(other.getAuthor())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasName()) {
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
        }
        if (hasScore()) {
          hash = (37 * hash) + SCORE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getScore()));
        }
        if (hasSize()) {
          hash = (37 * hash) + SIZE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getSize());
        }
        if (hasAuthor()) {
          hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
          hash = (53 * hash) + getAuthor().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static entity.proto.SearchModel.SearchResponse.DocumentStats parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(entity.proto.SearchModel.SearchResponse.DocumentStats prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code distributed.search.SearchResponse.DocumentStats}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:distributed.search.SearchResponse.DocumentStats)
          entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_DocumentStats_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_DocumentStats_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  entity.proto.SearchModel.SearchResponse.DocumentStats.class, entity.proto.SearchModel.SearchResponse.DocumentStats.Builder.class);
        }

        // Construct using entity.proto.SearchModel.SearchResponse.DocumentStats.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          score_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          size_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          author_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_DocumentStats_descriptor;
        }

        @java.lang.Override
        public entity.proto.SearchModel.SearchResponse.DocumentStats getDefaultInstanceForType() {
          return entity.proto.SearchModel.SearchResponse.DocumentStats.getDefaultInstance();
        }

        @java.lang.Override
        public entity.proto.SearchModel.SearchResponse.DocumentStats build() {
          entity.proto.SearchModel.SearchResponse.DocumentStats result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public entity.proto.SearchModel.SearchResponse.DocumentStats buildPartial() {
          entity.proto.SearchModel.SearchResponse.DocumentStats result = new entity.proto.SearchModel.SearchResponse.DocumentStats(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.score_ = score_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.size_ = size_;
            to_bitField0_ |= 0x00000004;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            to_bitField0_ |= 0x00000008;
          }
          result.author_ = author_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof entity.proto.SearchModel.SearchResponse.DocumentStats) {
            return mergeFrom((entity.proto.SearchModel.SearchResponse.DocumentStats)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(entity.proto.SearchModel.SearchResponse.DocumentStats other) {
          if (other == entity.proto.SearchModel.SearchResponse.DocumentStats.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasScore()) {
            setScore(other.getScore());
          }
          if (other.hasSize()) {
            setSize(other.getSize());
          }
          if (other.hasAuthor()) {
            bitField0_ |= 0x00000008;
            author_ = other.author_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasName()) {
            return false;
          }
          if (!hasScore()) {
            return false;
          }
          if (!hasSize()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          entity.proto.SearchModel.SearchResponse.DocumentStats parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (entity.proto.SearchModel.SearchResponse.DocumentStats) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        private double score_ ;
        /**
         * <code>required double score = 2;</code>
         */
        public boolean hasScore() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required double score = 2;</code>
         */
        public double getScore() {
          return score_;
        }
        /**
         * <code>required double score = 2;</code>
         */
        public Builder setScore(double value) {
          bitField0_ |= 0x00000002;
          score_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double score = 2;</code>
         */
        public Builder clearScore() {
          bitField0_ = (bitField0_ & ~0x00000002);
          score_ = 0D;
          onChanged();
          return this;
        }

        private long size_ ;
        /**
         * <code>required int64 size = 3;</code>
         */
        public boolean hasSize() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>required int64 size = 3;</code>
         */
        public long getSize() {
          return size_;
        }
        /**
         * <code>required int64 size = 3;</code>
         */
        public Builder setSize(long value) {
          bitField0_ |= 0x00000004;
          size_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 size = 3;</code>
         */
        public Builder clearSize() {
          bitField0_ = (bitField0_ & ~0x00000004);
          size_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object author_ = "";
        /**
         * <code>optional string author = 4;</code>
         */
        public boolean hasAuthor() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional string author = 4;</code>
         */
        public java.lang.String getAuthor() {
          java.lang.Object ref = author_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              author_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string author = 4;</code>
         */
        public com.google.protobuf.ByteString
            getAuthorBytes() {
          java.lang.Object ref = author_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            author_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string author = 4;</code>
         */
        public Builder setAuthor(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          author_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string author = 4;</code>
         */
        public Builder clearAuthor() {
          bitField0_ = (bitField0_ & ~0x00000008);
          author_ = getDefaultInstance().getAuthor();
          onChanged();
          return this;
        }
        /**
         * <code>optional string author = 4;</code>
         */
        public Builder setAuthorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          author_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:distributed.search.SearchResponse.DocumentStats)
      }

      // @@protoc_insertion_point(class_scope:distributed.search.SearchResponse.DocumentStats)
      private static final entity.proto.SearchModel.SearchResponse.DocumentStats DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new entity.proto.SearchModel.SearchResponse.DocumentStats();
      }

      public static entity.proto.SearchModel.SearchResponse.DocumentStats getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<DocumentStats>
          PARSER = new com.google.protobuf.AbstractParser<DocumentStats>() {
        @java.lang.Override
        public DocumentStats parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DocumentStats(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DocumentStats> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<DocumentStats> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public entity.proto.SearchModel.SearchResponse.DocumentStats getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DOCUMENTS_FIELD_NUMBER = 1;
    private java.util.List<entity.proto.SearchModel.SearchResponse.DocumentStats> documents_;
    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    public java.util.List<entity.proto.SearchModel.SearchResponse.DocumentStats> getDocumentsList() {
      return documents_;
    }
    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    public java.util.List<? extends entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder> 
        getDocumentsOrBuilderList() {
      return documents_;
    }
    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    public int getDocumentsCount() {
      return documents_.size();
    }
    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    public entity.proto.SearchModel.SearchResponse.DocumentStats getDocuments(int index) {
      return documents_.get(index);
    }
    /**
     * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
     */
    public entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder getDocumentsOrBuilder(
        int index) {
      return documents_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDocumentsCount(); i++) {
        if (!getDocuments(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < documents_.size(); i++) {
        output.writeMessage(1, documents_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < documents_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, documents_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof entity.proto.SearchModel.SearchResponse)) {
        return super.equals(obj);
      }
      entity.proto.SearchModel.SearchResponse other = (entity.proto.SearchModel.SearchResponse) obj;

      if (!getDocumentsList()
          .equals(other.getDocumentsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDocumentsCount() > 0) {
        hash = (37 * hash) + DOCUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getDocumentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static entity.proto.SearchModel.SearchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static entity.proto.SearchModel.SearchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static entity.proto.SearchModel.SearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static entity.proto.SearchModel.SearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static entity.proto.SearchModel.SearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static entity.proto.SearchModel.SearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static entity.proto.SearchModel.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static entity.proto.SearchModel.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(entity.proto.SearchModel.SearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code distributed.search.SearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:distributed.search.SearchResponse)
        entity.proto.SearchModel.SearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                entity.proto.SearchModel.SearchResponse.class, entity.proto.SearchModel.SearchResponse.Builder.class);
      }

      // Construct using entity.proto.SearchModel.SearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDocumentsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (documentsBuilder_ == null) {
          documents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          documentsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return entity.proto.SearchModel.internal_static_distributed_search_SearchResponse_descriptor;
      }

      @java.lang.Override
      public entity.proto.SearchModel.SearchResponse getDefaultInstanceForType() {
        return entity.proto.SearchModel.SearchResponse.getDefaultInstance();
      }

      @java.lang.Override
      public entity.proto.SearchModel.SearchResponse build() {
        entity.proto.SearchModel.SearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public entity.proto.SearchModel.SearchResponse buildPartial() {
        entity.proto.SearchModel.SearchResponse result = new entity.proto.SearchModel.SearchResponse(this);
        int from_bitField0_ = bitField0_;
        if (documentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            documents_ = java.util.Collections.unmodifiableList(documents_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.documents_ = documents_;
        } else {
          result.documents_ = documentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof entity.proto.SearchModel.SearchResponse) {
          return mergeFrom((entity.proto.SearchModel.SearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(entity.proto.SearchModel.SearchResponse other) {
        if (other == entity.proto.SearchModel.SearchResponse.getDefaultInstance()) return this;
        if (documentsBuilder_ == null) {
          if (!other.documents_.isEmpty()) {
            if (documents_.isEmpty()) {
              documents_ = other.documents_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDocumentsIsMutable();
              documents_.addAll(other.documents_);
            }
            onChanged();
          }
        } else {
          if (!other.documents_.isEmpty()) {
            if (documentsBuilder_.isEmpty()) {
              documentsBuilder_.dispose();
              documentsBuilder_ = null;
              documents_ = other.documents_;
              bitField0_ = (bitField0_ & ~0x00000001);
              documentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDocumentsFieldBuilder() : null;
            } else {
              documentsBuilder_.addAllMessages(other.documents_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getDocumentsCount(); i++) {
          if (!getDocuments(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        entity.proto.SearchModel.SearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (entity.proto.SearchModel.SearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<entity.proto.SearchModel.SearchResponse.DocumentStats> documents_ =
        java.util.Collections.emptyList();
      private void ensureDocumentsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          documents_ = new java.util.ArrayList<entity.proto.SearchModel.SearchResponse.DocumentStats>(documents_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          entity.proto.SearchModel.SearchResponse.DocumentStats, entity.proto.SearchModel.SearchResponse.DocumentStats.Builder, entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder> documentsBuilder_;

      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public java.util.List<entity.proto.SearchModel.SearchResponse.DocumentStats> getDocumentsList() {
        if (documentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(documents_);
        } else {
          return documentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public int getDocumentsCount() {
        if (documentsBuilder_ == null) {
          return documents_.size();
        } else {
          return documentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public entity.proto.SearchModel.SearchResponse.DocumentStats getDocuments(int index) {
        if (documentsBuilder_ == null) {
          return documents_.get(index);
        } else {
          return documentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public Builder setDocuments(
          int index, entity.proto.SearchModel.SearchResponse.DocumentStats value) {
        if (documentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentsIsMutable();
          documents_.set(index, value);
          onChanged();
        } else {
          documentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public Builder setDocuments(
          int index, entity.proto.SearchModel.SearchResponse.DocumentStats.Builder builderForValue) {
        if (documentsBuilder_ == null) {
          ensureDocumentsIsMutable();
          documents_.set(index, builderForValue.build());
          onChanged();
        } else {
          documentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public Builder addDocuments(entity.proto.SearchModel.SearchResponse.DocumentStats value) {
        if (documentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentsIsMutable();
          documents_.add(value);
          onChanged();
        } else {
          documentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public Builder addDocuments(
          int index, entity.proto.SearchModel.SearchResponse.DocumentStats value) {
        if (documentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentsIsMutable();
          documents_.add(index, value);
          onChanged();
        } else {
          documentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public Builder addDocuments(
          entity.proto.SearchModel.SearchResponse.DocumentStats.Builder builderForValue) {
        if (documentsBuilder_ == null) {
          ensureDocumentsIsMutable();
          documents_.add(builderForValue.build());
          onChanged();
        } else {
          documentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public Builder addDocuments(
          int index, entity.proto.SearchModel.SearchResponse.DocumentStats.Builder builderForValue) {
        if (documentsBuilder_ == null) {
          ensureDocumentsIsMutable();
          documents_.add(index, builderForValue.build());
          onChanged();
        } else {
          documentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public Builder addAllDocuments(
          java.lang.Iterable<? extends entity.proto.SearchModel.SearchResponse.DocumentStats> values) {
        if (documentsBuilder_ == null) {
          ensureDocumentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, documents_);
          onChanged();
        } else {
          documentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public Builder clearDocuments() {
        if (documentsBuilder_ == null) {
          documents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          documentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public Builder removeDocuments(int index) {
        if (documentsBuilder_ == null) {
          ensureDocumentsIsMutable();
          documents_.remove(index);
          onChanged();
        } else {
          documentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public entity.proto.SearchModel.SearchResponse.DocumentStats.Builder getDocumentsBuilder(
          int index) {
        return getDocumentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder getDocumentsOrBuilder(
          int index) {
        if (documentsBuilder_ == null) {
          return documents_.get(index);  } else {
          return documentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public java.util.List<? extends entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder> 
           getDocumentsOrBuilderList() {
        if (documentsBuilder_ != null) {
          return documentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(documents_);
        }
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public entity.proto.SearchModel.SearchResponse.DocumentStats.Builder addDocumentsBuilder() {
        return getDocumentsFieldBuilder().addBuilder(
            entity.proto.SearchModel.SearchResponse.DocumentStats.getDefaultInstance());
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public entity.proto.SearchModel.SearchResponse.DocumentStats.Builder addDocumentsBuilder(
          int index) {
        return getDocumentsFieldBuilder().addBuilder(
            index, entity.proto.SearchModel.SearchResponse.DocumentStats.getDefaultInstance());
      }
      /**
       * <code>repeated .distributed.search.SearchResponse.DocumentStats documents = 1;</code>
       */
      public java.util.List<entity.proto.SearchModel.SearchResponse.DocumentStats.Builder> 
           getDocumentsBuilderList() {
        return getDocumentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          entity.proto.SearchModel.SearchResponse.DocumentStats, entity.proto.SearchModel.SearchResponse.DocumentStats.Builder, entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder> 
          getDocumentsFieldBuilder() {
        if (documentsBuilder_ == null) {
          documentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              entity.proto.SearchModel.SearchResponse.DocumentStats, entity.proto.SearchModel.SearchResponse.DocumentStats.Builder, entity.proto.SearchModel.SearchResponse.DocumentStatsOrBuilder>(
                  documents_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          documents_ = null;
        }
        return documentsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:distributed.search.SearchResponse)
    }

    // @@protoc_insertion_point(class_scope:distributed.search.SearchResponse)
    private static final entity.proto.SearchModel.SearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new entity.proto.SearchModel.SearchResponse();
    }

    public static entity.proto.SearchModel.SearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
      @java.lang.Override
      public SearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public entity.proto.SearchModel.SearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributed_search_SearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributed_search_SearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributed_search_SearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributed_search_SearchResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributed_search_SearchResponse_DocumentStats_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributed_search_SearchResponse_DocumentStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCprojects/searchengine/src/main/java/en" +
      "tity/proto/searchengine.proto\022\022distribut" +
      "ed.search\"$\n\rSearchRequest\022\023\n\013search_ter" +
      "m\030\001 \002(\t\"\241\001\n\016SearchResponse\022C\n\tdocuments\030" +
      "\001 \003(\01320.distributed.search.SearchRespons" +
      "e.DocumentStats\032J\n\rDocumentStats\022\014\n\004name" +
      "\030\001 \002(\t\022\r\n\005score\030\002 \002(\001\022\014\n\004size\030\003 \002(\003\022\016\n\006a" +
      "uthor\030\004 \001(\tB\033\n\014entity.protoB\013SearchModel"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_distributed_search_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_distributed_search_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributed_search_SearchRequest_descriptor,
        new java.lang.String[] { "SearchTerm", });
    internal_static_distributed_search_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_distributed_search_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributed_search_SearchResponse_descriptor,
        new java.lang.String[] { "Documents", });
    internal_static_distributed_search_SearchResponse_DocumentStats_descriptor =
      internal_static_distributed_search_SearchResponse_descriptor.getNestedTypes().get(0);
    internal_static_distributed_search_SearchResponse_DocumentStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributed_search_SearchResponse_DocumentStats_descriptor,
        new java.lang.String[] { "Name", "Score", "Size", "Author", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
